# Generated by Django 5.1 on 2025-06-19 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_robimar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arriendo',
            name='valor_total',
        ),
        migrations.RemoveField(
            model_name='arriendodetalle',
            name='valor_unitario',
        ),
        migrations.AlterField(
            model_name='material',
            name='stock_disponible',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='material',
            name='stock_total',
            field=models.PositiveIntegerField(),
        ),
    ]
