# Generated by Django 5.1 on 2025-06-23 17:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_robimar', '0002_remove_arriendo_valor_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(error_messages={'invalid': 'Debe ingresar un correo válido en el formato ejemplo@dominio.com'}, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='El número de teléfono debe contener exactamente 9 dígitos numéricos.', regex='^\\d{9}$')]),
        ),
    ]
